[client]
port=3306
default-character-set=utf8mb4

[mysqld]
port=3306
basedir=E:/MySQL/mysql-8.0.45-winx64
datadir=E:/sky/mysql_data
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default_authentication_plugin=mysql_native_password
max_connections=200
sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION

[mysql]
default-character-set=utf8mb4
