export const appCopy = {
  brand: {
    name: '苍穹外卖',
    consoleName: '苍穹运营台',
  },
  notFound: {
    eyebrow: 'Sky Take Out',
    title: '这条路还没有铺好。',
    description: '你可以先回到顾客端继续点餐，或者去后台继续处理经营任务。',
    customerAction: '去顾客端',
    consoleAction: '去后台',
  },
  customerShell: {
    eyebrow: 'Customer / Mobile Ordering',
    title: '苍穹外卖',
    description: '移动端点餐入口，顾客第一次进入会自动完成 mock 登录。',
    sessionPending: '正在建立顾客会话',
    sessionReady: '当前用户 ID',
    connectTitle: '正在连接顾客侧会话',
    connectBody: '前端正在按当前 mock 登录策略自动向 /user/user/login 申请顾客 token。',
    errorTitle: '顾客登录失败',
    errorBody: '无法自动创建顾客会话，请先确认后端 8080 已启动。',
    loadingTitle: '正在初始化顾客入口',
    loadingBody: '顾客端正在准备 token、读取营业状态，并预热页面需要的查询。',
    nav: {
      home: '点餐',
      orders: '订单中心',
      addresses: '地址簿',
      profile: '个人区',
    },
  },
  consoleShell: {
    eyebrow: 'Console / Operations Hub',
    title: '苍穹运营台',
    description: '同一后台里切换商家运营视图和完整管理员视图，接口仍然走现有 admin token。',
    modeTitle: '视角切换',
    navTitle: '主导航',
    profileTitle: '当前身份',
    missingProfileTitle: '资料缺失',
    missingProfileBody: '当前没有缓存管理员资料，建议重新登录。',
    logout: '退出后台',
    merchantMode: '运营台',
    adminMode: '管理员',
    nav: {
      workspace: '工作台',
      orders: '订单中心',
      categories: '分类管理',
      dishes: '菜品管理',
      setmeals: '套餐管理',
      shop: '店铺状态',
      reports: '报表中心',
      employees: '员工管理',
    },
  },
  runbook: {
    serviceErrorTitle: '服务还没准备好',
    serviceErrorBody: '请先启动后端 8080、Redis 和 Nginx，再刷新当前页面。',
  },
} as const;
