export const appCopy = {
  brand: {
    name: '苍穹外卖',
    consoleName: '苍穹运营台',
  },
  notFound: {
    eyebrow: 'Sky Take Out',
    title: '这条路还没有铺好。',
    description: '你可以先回到顾客端继续点餐，或者去后台继续处理经营任务。',
    customerAction: '去顾客端',
    consoleAction: '去后台',
  },
  customerShell: {
    eyebrow: 'Customer / Mobile Ordering',
    title: '苍穹外卖',
    description: '移动端点餐入口，顾客第一次进入会自动完成 mock 登录。',
    sessionPending: '正在建立顾客会话',
    sessionReady: '当前用户 ID',
    connectTitle: '正在连接顾客侧会话',
    connectBody: '前端正在按当前 mock 登录策略自动向 /user/user/login 申请顾客 token。',
    errorTitle: '顾客登录失败',
    errorBody: '无法自动创建顾客会话，请先确认后端 8080 已启动。',
    loadingTitle: '正在初始化顾客入口',
    loadingBody: '顾客端正在准备 token、读取营业状态，并预热页面需要的查询。',
    nav: {
      home: '点餐',
      orders: '订单中心',
      addresses: '地址簿',
      profile: '个人区',
    },
  },
  consoleShell: {
    eyebrow: 'Console / Operations Hub',
    title: '苍穹运营台',
    description: '同一后台里切换商家运营视图和完整管理员视图，接口仍然走现有 admin token。',
    modeTitle: '视角切换',
    navTitle: '主导航',
    profileTitle: '当前身份',
    missingProfileTitle: '资料缺失',
    missingProfileBody: '当前没有缓存管理员资料，建议重新登录。',
    logout: '退出后台',
    merchantMode: '运营台',
    adminMode: '管理员',
    nav: {
      workspace: '工作台',
      orders: '订单中心',
      categories: '分类管理',
      dishes: '菜品管理',
      setmeals: '套餐管理',
      shop: '店铺状态',
      reports: '报表中心',
      employees: '员工管理',
    },
  },
  consoleFeedback: {
    saveSuccess: (entity: string) => `${entity}已保存，列表已经同步刷新。`,
    saveErrorTitle: (entity: string) => `${entity}保存失败`,
    statusSuccess: (entity: string, label: string) => `${entity}已${label}，当前状态已经同步刷新。`,
    statusErrorTitle: (entity: string, label: string) => `${entity}${label}失败`,
    deleteSuccess: (entity: string) => `${entity}已删除，列表已经同步刷新。`,
    deleteErrorTitle: (entity: string) => `${entity}删除失败`,
    uploadSuccess: '图片已上传成功，现在可以继续保存表单。',
    uploadErrorTitle: '图片上传失败',
    orderActionSuccess: (action: string, orderNumber: string) => `订单 ${orderNumber} 已执行“${action}”操作。`,
    orderActionErrorTitle: (action: string) => `订单${action}失败`,
    shopStatusSuccess: (isRunning: boolean) => isRunning ? '店铺已切换为营业中，顾客端可以继续下单。' : '店铺已切换为打烊中，顾客端下单入口会被禁用。',
    shopStatusErrorTitle: '店铺状态切换失败',
    exportSuccess: '报表文件已开始下载，你可以继续切换日期范围查看趋势。',
    exportErrorTitle: '报表导出失败',
  },
  runbook: {
    serviceErrorTitle: '服务还没准备好',
    serviceErrorBody: '请先启动后端 8080、Redis 和 Nginx，再刷新当前页面。',
  },
  customerHome: {
    heroTitle: '把点餐首页做成真正能成交的移动入口',
    heroDescription: '顾客端这版优先保证真正能点单：营业状态、分类、菜品、套餐、购物车、地址簿和订单动作都直接连现在的 user 接口。',
    openCart: '打开购物车',
    viewOrders: '查看订单',
    cartCountLabel: '购物车件数',
    cartCountHint: '来自购物车实时汇总',
    cartAmountLabel: '当前合计',
    cartAmountHint: '当前结算口径',
    addressLabel: '收货地址',
    addressHint: '当前默认地址',
    userLabel: '当前顾客',
    userHint: 'mock 登录已接现有 user token',
    shopClosedTitle: '店铺当前打烊中',
    shopClosedBody: '后端返回店铺当前不营业，所以首页仍可浏览，但会禁用提交订单。',
    shopOpenTitle: '门店状态正常',
    shopOpenBody: '当前门店营业正常，你可以直接把菜品或套餐加入购物车，再提交订单。',
    serviceErrorTitle: '点餐首页加载失败',
    serviceErrorBody: '顾客端分类、菜品、套餐或购物车接口暂时不可用，请先确认后端 8080 与用户端接口已经启动。',
    dishSectionTitle: '今日点什么',
    dishSectionDescription: '分类切换会触发对应接口查询；为了让移动端单手操作更顺，分类和菜品都尽量压成卡片流。',
    setmealSectionTitle: '套餐专区',
    setmealSectionDescription: '套餐专区会继续使用现有 user/setmeal/list。第一版先把列表、加购和价格反馈做顺。',
    cartTitle: '购物车与提交订单',
    cartDescription: '这里直接串上购物车、默认地址、备注和提交订单接口，方便你马上从顾客视角走闭环。',
    emptyCartTitle: '购物车还空着',
    emptyCartBody: '先选几道菜，购物车才会在这里出现真实明细。',
    noDefaultAddressTitle: '下单前先补一个默认地址',
    noDefaultAddressBody: '购物车和菜品都准备好了，只差一个默认地址就能直接提交订单。',
    noDefaultAddressAction: '去地址簿设置',
    addressReady: (consignee: string) => `默认地址 · ${consignee}`,
    checkoutHint: '提交后不会自动支付，你可以去订单中心触发 mock 支付。',
    clearCart: '清空购物车',
    submitOrder: '提交订单',
    submittingOrder: '提交中…',
    stickyDetails: '查看明细',
    stickyCheckout: '去结算',
    stickyAddressAction: '去补地址',
    stickyClosed: '门店已打烊',
    stickyEmpty: '先去选菜',
    submitSuccessBody: (orderNumber: string) => `订单 ${orderNumber} 已创建，现在去订单中心完成支付。`,
    journeyTitle: '四步完成一次下单',
    journeyDescription: '把“选菜、补地址、提交订单、完成支付”拆成短步骤，顾客更容易判断下一步该做什么。',
    journeyBrowseTitle: '先选好想吃的菜',
    journeyBrowseBody: '菜品和套餐都已经连真实接口，先把购物车装起来。',
    journeyAddressTitle: '补一个默认地址',
    journeyAddressBody: '默认地址一旦设置好，结算就不会再被卡住。',
    journeySubmitTitle: '提交订单',
    journeySubmitBody: '备注、餐具份数和打包费都已经进同一条结算链路。',
    journeyPayTitle: '去订单中心完成支付',
    journeyPayBody: '当前支付仍是 mock 流程，但状态回写和列表刷新都已经接好。',
    addSuccessTitle: '已加入购物车',
    addSuccessBody: (name: string) => `${name} 已加入购物车，可以继续加菜或直接去结算。`,
    removeSuccessTitle: '已更新购物车',
    removeSuccessBody: (name: string) => `${name} 的数量已经更新。`,
    clearSuccessTitle: '购物车已清空',
    clearSuccessBody: '当前购物车内容已经清空，可以重新挑选菜品。',
  },
  customerOrders: {
    heroTitle: '订单中心会把真实状态、支付、催单和再来一单连起来',
    heroDescription: '这里直接使用 historyOrders / orderDetail / payment / reminder / cancel / repetition，顾客端常用动作都能在一页里完成。',
    filters: [
      { label: '全部订单', value: null },
      { label: '待支付', value: 1 },
      { label: '待接单', value: 2 },
      { label: '派送中', value: 4 },
      { label: '已完成', value: 5 },
      { label: '已取消', value: 6 },
    ] as const,
    detailOpen: '展开详情',
    detailClose: '收起详情',
    detailTitle: '订单详情',
    detailLoadingTitle: '正在读取订单详情',
    detailLoadingBody: '稍等一下，前端正在补全这笔订单的明细、地址和备注。',
    detailErrorTitle: '订单详情加载失败',
    detailErrorBody: '这笔订单的详情暂时没有补全成功，你可以稍后再试一次。',
    emptyAllTitle: '你还没有下过单',
    emptyAllBody: '先去首页点一单，订单中心才会开始出现真实内容。',
    emptyFilteredTitle: '这个筛选条件下没有订单',
    emptyFilteredBody: '换个状态筛选看看，或者回到首页继续完成下单。',
    payAction: '立即支付',
    remindAction: '催单',
    cancelAction: '取消',
    repeatAction: '再来一单',
    payStatusLabel: '支付状态',
    consigneeLabel: '收货人',
    orderAmountLabel: '订单金额',
    deliveryAddressLabel: '送达地址',
    remarkLabel: '备注',
    packAmountLabel: '打包费',
    tablewareLabel: '餐具份数',
    paymentSuccessTitle: '支付状态已更新',
    paymentSuccessBody: (number: string) => `订单 ${number} 已标记为已支付。`,
    remindSuccessTitle: '催单已发送',
    remindSuccessBody: (number: string) => `已向门店发送订单 ${number} 的催单提醒。`,
    cancelSuccessTitle: '订单已取消',
    cancelSuccessBody: (number: string) => `订单 ${number} 已取消，列表状态已同步刷新。`,
    repeatSuccessTitle: '同款已重新加入购物车',
    repeatSuccessBody: (number: string) => `订单 ${number} 的商品已经放回购物车，现在可以回首页继续确认。`,
    repeatSuccessAction: '回到点餐页',
    createdFromCheckoutTitle: '订单已就绪，去完成支付吧',
    gotoMenuAction: '回到点餐首页',
    summaryTitle: '订单状态总览',
    summaryDescription: '把待支付、履约中和已完成分组摆出来，顾客不需要再逐条猜状态。',
    pendingCountLabel: '待支付',
    activeCountLabel: '履约中',
    finishedCountLabel: '已完成',
    canceledCountLabel: '已取消',
    liveHintIdle: '现在还没有待处理订单，随时可以回到首页再点一单。',
    liveHintBusy: '订单中心已经接到真实回写，现在可以继续支付、催单或查看详情。',
  },
  customerAddresses: {
    heroTitle: '地址簿要尽量轻，动作却要完整',
    heroDescription: '地址簿页把新增、修改、删除、设默认这几条接口合到一页，顾客可以直接把默认地址准备好再去下单。',
    createAction: '新增地址',
    modalCreateTitle: '新增收货地址',
    modalEditTitle: '更新送达地址',
    modalDescription: '前端会先保存地址，再按你的选择切换默认地址。',
    checkoutHintTitle: '还差一个默认地址',
    checkoutHintBody: '补一个默认地址后，你就可以回到首页直接提交订单。',
    checkoutHintAction: '回到点餐页',
    saveSuccessTitle: '地址已保存',
    saveSuccessBody: '地址簿已经更新，可以继续挑选菜品或回头补默认地址。',
    saveDefaultSuccessTitle: '默认地址已准备好',
    saveDefaultSuccessBody: '现在可以回到首页继续提交订单了。',
    deleteSuccessTitle: '地址已删除',
    deleteSuccessBody: '这条地址已经从地址簿中移除。',
    defaultSuccessTitle: '默认地址已切换',
    defaultSuccessBody: '新的默认地址已经生效，结算时会直接带入。',
    emptyTitle: '地址簿还没有内容',
    emptyBody: '目前还没有地址，先新增一个默认地址，点餐和下单就会顺很多。',
  },
  customerProfile: {
    heroTitle: '个人区负责把当前会话状态讲清楚',
    heroDescription: '第一版个人区不追求做得很重，重点是把当前用户、门店状态和常用入口都放在一块，方便联调。',
  },
} as const;
